graphql_tutorial/graphql_tutorial/urls.py
from django.contrib import admin
from graphene_django.views import GraphQLView
from django.urls import path, include
from .schema import schema
urlpatterns = [
    path('snippet/', include('sampleapp.urls', namespace="snippets")),
    path('graphql', GraphQLView.as_view(
        graphiql=True,
        schema=schema
    )),
    path('admin/', admin.site.urls),
]

graphql_tutorial/sampleapp/urls.py
from django.urls import path, include
from . import views

app_name = 'sampleapp'
urlpatterns = [
    path('', views.SnippetListView.as_view(), name='list'),
    path('<int:pk>/', views.SnippetDetailView.as_view(), name='detail')
]

graphql_tutorial/sampleapp/models.py
from django.db import models

class Snippet(models.Model):
    title=models.CharField(max_length=100)
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
        
    def body_preview(self):
        return self.body[:50]

graphql_tutorial/sampleapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Snippet
from django.views import View
from django.views.generic import ListView, DetailView


class SnippetListView(ListView):
    model = Snippet
    template_name = 'snippets/snippet_list.html'


class SnippetDetailView(DetailView):
    model = Snippet
    template_name = 'snippets/snippet_detail.html'

graphql_tutorial/sampleapp/templates/snippets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
  {% block content %}

  {% endblock content %}
</body>
</html>

graphql_tutorial/sampleapp/templates/snippets/snippet_detail.html
{% extends 'snippets/base.html' %}

{% block title %}Snippet Detail{% endblock title %}

{% block content %}

<h1>{{ snippet.title }}</h1>

<pre>
  {{ snippet.body_preview }}
</pre>

{% endblock content %}

graphql_tutorial/sampleapp/templates/snippets/snippet_list.html
{% extends 'snippets/base.html' %}

{% block title %}Snippet List{% endblock title %}

{% block content %}

<ul>
  {% for snippet in snippet_list %}
    <li>
      <a href="{% url 'snippets:detail' snippet.id %}">{{ snippet.title }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock content %}